plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'net.exylia'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/groups/public/' }
    maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven {
        name = "minecraft-libraries"
        url = uri("https://libraries.minecraft.net")
    }
}

dependencies {
    compileOnly 'com.zaxxer:HikariCP:5.1.0'
    compileOnly 'org.xerial:sqlite-jdbc:3.45.2.0'
    compileOnly 'mysql:mysql-connector-java:8.0.33'
    compileOnly 'com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.5'
    compileOnly 'redis.clients:jedis:5.1.0'
    compileOnly 'org.apache.commons:commons-pool2:2.12.0'
    compileOnly 'org.slf4j:slf4j-api:2.0.9'
    compileOnly 'org.slf4j:slf4j-simple:2.0.9'
    compileOnly 'com.mojang:authlib:1.5.25'
    compileOnly 'net.kyori:adventure-api:4.17.0'
    compileOnly 'net.kyori:adventure-platform-bukkit:4.3.4'
    compileOnly 'net.kyori:adventure-text-minimessage:4.17.0'
    compileOnly 'net.kyori:adventure-text-serializer-legacy:4.17.0'
    compileOnly 'org.mongodb:mongodb-driver-sync:4.11.0'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}

shadowJar {
    archiveClassifier.set('')
    // Ya no incluimos Adventure aquí
}

build {
    dependsOn shadowJar
}