plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id("io.freefair.lombok") version "8.14"
}

group = 'net.exylia'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/groups/public/' }
    maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url "https://maven.enginehub.org/repo/" }
    maven {
        name = "minecraft-libraries"
        url = uri("https://libraries.minecraft.net")
    }
}

dependencies {
    compileOnly 'com.zaxxer:HikariCP:5.1.0'
    compileOnly 'org.xerial:sqlite-jdbc:3.45.2.0'
    compileOnly 'mysql:mysql-connector-java:8.0.33'
    compileOnly 'com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.5'
    compileOnly 'redis.clients:jedis:5.1.0'
    compileOnly 'org.apache.commons:commons-pool2:2.12.0'
    compileOnly 'org.slf4j:slf4j-api:2.0.9'
    compileOnly 'org.slf4j:slf4j-simple:2.0.9'
    compileOnly 'com.mojang:authlib:1.5.25'
    compileOnly 'net.kyori:adventure-api:4.17.0'
    compileOnly 'net.kyori:adventure-platform-bukkit:4.3.4'
    compileOnly 'net.kyori:adventure-text-minimessage:4.17.0'
    compileOnly 'net.kyori:adventure-text-serializer-legacy:4.17.0'
    compileOnly 'org.mongodb:mongodb-driver-sync:4.11.0'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7'
    compileOnly 'com.fastasyncworldedit:FastAsyncWorldEdit-Core:2.8.4'
    compileOnly 'com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit:2.8.4'
    compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.7'
    implementation 'com.github.lalyos:jfiglet:0.0.9'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            groupId = 'net.exylia'
            artifactId = 'ExyliaCommons'
            version = '1.0.0'

            pom {
                name = 'ExyliaCommons'
                description = 'Common utilities for Exylia plugins'
                url = 'https://github.com/Exylia-Plugins/ExyliaCommons'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'DiGround-s'
                        name = 'DiGround-s'
                    }
                }

                scm {
                    connection = 'scm:git:git://github.com/Exylia-Plugins/ExyliaCommons.git'
                    developerConnection = 'scm:git:ssh://github.com:Exylia-Plugins/ExyliaCommons.git'
                    url = 'https://github.com/Exylia-Plugins/ExyliaCommons'
                }
            }
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Exylia-Plugins/ExyliaCommons")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME") ?: "DiGround-s"
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
    }
}

// Agregar task para sources
java {
    withSourcesJar()
}

shadowJar {
    archiveClassifier.set('')
    // Solo incluye las dependencias implementation
    configurations = [project.configurations.runtimeClasspath]
}

// Asegurarse de que el shadowJar se ejecute antes de publicar
tasks.named('publishMavenPublicationToGitHubPackagesRepository') {
    dependsOn shadowJar
}

build {
    dependsOn shadowJar
}