# Only for development purposes
debug: false

text:
  automatic-font: "small" # small or none
  force-in-upper-case: true

date-formatter:
  default-pattern: "dd/MM/yyyy HH:mm:ss"
  date-pattern: "dd/MM/yyyy"
  time-pattern: "HH:mm:ss"
  language: "en" # en, es
  use-iso: false

time-formatter:
  zero-text: "{success}Now"
  show-milliseconds: true
  precision: 1
  language: "en" # en, es
  compact-mode: false
  auto-detect-seconds: true
  force-show-zero-decimals: false